### ISSUE TITLE
Latest commit crashes build on Manjaro

### ISSUE THREAD

**Issue by xcom169** [dethrace-labs/dethrace#110]
Hello All!

Lately the build is not working on Linux : 

Error:
Consolidate compiler generated dependencies of target harness
[ 49%] Building C object src/harness/CMakeFiles/harness.dir/os/linux.c.o
/home/csabesz/Documents/dethrace/src/harness/os/linux.c:20:10: fatal error: sys/sysctl.h: No such file or directory
   20 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

**Comment by madebr** [comment]
Indeed, I also noticed this.
A fix is included in https://github.com/dethrace-labs/dethrace/pull/107

`sys/sysctl.h` is removed in recent glibc versions: https://sourceware.org/git/gitweb.cgi?p=glibc.git;h=076f09afbac1aa57756faa7a8feadb7936a724e4
Looks like ubuntu on the github action is using an older version.
