### ISSUE TITLE
Entrance camera has incorrect pitch

### ISSUE THREAD

**Issue by madebr** [dethrace-labs/dethrace#112]
When entering a new race, the camera has the wrong pitch.
It should point downwards towards the car.

Workaround:
Remove all opponents by setting `OPPONENT_COUNT` to `0`

https://github.com/dethrace-labs/dethrace/blob/80f5fceff92e908d47a30567b0a34c26e8ce030c/src/DETHRACE/constants.h#L297

Another workaround (fake fix):
Modify `if (swoop)` to `if (0)`

https://github.com/dethrace-labs/dethrace/blob/3980d9e9c92259770135f8d9a3428b2fb4c928c2/src/DETHRACE/common/car.c#L4844

The root cause is the missing implementation for multiple cars: all cars (except the player) have coordinates (0.f, 0.f, 0.f).
Because the entrance camera will point at the average of these positions, it will point at (0, 0, 0), not the real location.

**Comment by dethrace-labs** [comment]
This is now fixed with the implementation of AI cars! 🎉

**Comment by madebr** [comment]
Oh yes, I didn't even realize this was fixed when trying current master!
Nice job!!!
:partying_face:
