### ISSUE TITLE
Build fails with 1 error on Windows

### ISSUE THREAD

**Issue by whouishere** [dethrace-labs/dethrace#141]
```
src/harness/os/windows.c:52:12: error: unused variable 'hFind' [-Werror,-Wunused-variable]
    HANDLE hFind = NULL;
           ^
1 error generated.
```

Commenting said line out works out just fine though.
May I create a simple PR fixing this? Or should we circumvent this from another way?

**Comment by madebr** [comment]
Yes please do.
The `HANDLE` is not used anymore.
