### ISSUE TITLE
No need to draw everything 3 times

### ISSUE THREAD

**Issue by madebr** [dethrace-labs/dethrace#143]
https://github.com/dethrace-labs/dethrace/blob/b3bdbb26503ac435b8877ccff4a6418884640b0e/src/DETHRACE/common/graphics.c#L1607

This for-loop causes the scene to be drawn 1 to 3 times, depending whether the map mode is enabled or not.
The original executable has a loop here, but when I replace this line with a simple `if (1) {`, everything keeps working 100% fine.

**Comment by dethrace-labs** [comment]
I noticed that too, so strange! No idea why the original executable does that. I've seen it in all the executables I've looked at

**Comment by madebr** [comment]
It would be interesting to patch this in an executable and measure whether there is a difference in frame rate.

**Comment by dethrace-labs** [comment]
Interestingly, in `VOODOO2C.exe`, its slightly different:

```
v27 = !gMap_mode || gSome_var_only_set_in_voodoo_rendering_mode ? 1 : 3
```

So if it is in voodoo mode, the triple rendering doesn't happen. Its weird though - why go to the trouble of updating the check instead of removing the loop entirely? 🤔  

/ @madebr

**Comment by dethrace-labs** [comment]
Maybe they were working around a bug in the software renderer

**Comment by madebr** [comment]
I looked a bit in `3DFX.EXE`, and found the `gSome_var_only_set_in_voodoo_rendering_mode` variale is used in only 1 other funtion: `ReinitialiseRenderStuff`.
```c
void ReinitialiseRenderStuff() {
    int x_diff;
    int y_diff;
    LOG_TRACE("()");

    if (gProgram_state.cockpit_on) {
        gProgram_state.current_render_left = gProgram_state.current_car.render_left[gProgram_state.cockpit_image_index];
        gProgram_state.current_render_top = gProgram_state.current_car.render_top[gProgram_state.cockpit_image_index];
        gProgram_state.current_render_right = gProgram_state.current_car.render_right[gProgram_state.cockpit_image_index];
        gProgram_state.current_render_bottom = gProgram_state.current_car.render_bottom[gProgram_state.cockpit_image_index];
    } else {
        if (gSome_var_only_set_in_voodoo_rendering_mode) {
            gProgram_state.current_render_top = 0;
            gProgram_state.current_render_left = 0;
            gProgram_state.current_render_right = gGraf_specs[gGraf_spec_index].total_width;
            gProgram_state.current_render_bottom = gGraf_specs[gGraf_spec_index].total_height;
        } else {
            gProgram_state.current_render_top = (gGraf_specs[gGraf_spec_index].total_height / 18 & ~1) * gRender_indent;
            gProgram_state.current_render_left = (gGraf_specs[gGraf_spec_index].total_width / 18 & ~3) * gRender_indent;
            x_diff = gGraf_specs[gGraf_spec_index].total_width - gProgram_state.current_render_left;
            y_diff = gGraf_specs[gGraf_spec_index].total_height - gProgram_state.current_render_top;
            gProgram_state.current_render_right = x_diff;
            gProgram_state.current_render_bottom = y_diff;
        }
    }
}
```
So your theory of it being render specific sounds very credible.
