### ISSUE TITLE
Opponents can spawn stuck in air

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#179]
When game spawns opponents, sometimes they spawn hovering little over the ground. In some spots they spawn stuck over the ground, in other cases they violently move forward and backward a little while still stuck in the air.

Hitting opponent makes them fall to the ground, but also releases whatever energy they've had, making them dart foward.

Opponent stuck in air in Icing on the Quake race:

<img width="1440" alt="Zrzut ekranu 2022-09-27 o 19 46 32" src="https://user-images.githubusercontent.com/750553/192604859-1be06bdd-9dfd-4da1-bfbe-141aea829587.png">

**Comment by madebr** [comment]
I haven't seen this happen for a while now. Does this still happen?

**Comment by madebr** [comment]
If anybody sees this again with current main, please leave a message here or create a new issue.
