### ISSUE TITLE
Mother Trucker is not rendered correctly

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#180]
In dethrace car is missing front grill and some other features:

<img width="1440" alt="Zrzut ekranu 2022-09-27 o 20 38 28" src="https://user-images.githubusercontent.com/750553/192609257-81e87532-6426-4388-96e6-ff85eef6a546.png">

**Comment by zear** [comment]
Can't reproduce anymore:
![truck](https://user-images.githubusercontent.com/510643/205274857-5217ca7a-ec82-470e-8d64-23b445942b8f.png)
