### ISSUE TITLE
Prisoner ped from SP running not rendered correctly

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#181]
<img width="1440" alt="Zrzut ekranu 2022-09-27 o 22 19 16" src="https://user-images.githubusercontent.com/750553/192628069-c8971ed8-7895-4d6f-b7e9-b5d5f40b8ef1.png">
<img width="1440" alt="Zrzut ekranu 2022-09-27 o 22 07 35" src="https://user-images.githubusercontent.com/750553/192628134-b9571d41-2138-42b7-b238-2bc74aa1df62.png">

**Comment by madebr** [comment]
This is fixed in https://github.com/dethrace-labs/dethrace/commit/fc656252728d809cf51f1bcf866a54611d3cdd1c.
Please retest with current master, or using the next release.

**Comment by madebr** [comment]
If you're unable to test, what race + location is this?
I can check this as well.

**Comment by rafalp** [comment]
@madebr this is second race from splat pack - prison break

**Comment by madebr** [comment]
Thanks, I'm more a fan of the original levels :wink: 

It looks like this has been fixed in current master:
![DUMP0018b](https://user-images.githubusercontent.com/4138939/193151136-e119eb5e-20f1-40d3-bd58-e7615fcd92a7.PNG)

**Comment by dethrace-labs** [comment]
nice, I hoped that would be the resolution :)

**Comment by dethrace-labs** [comment]
We'll do another point release next week, have a lot of new fixes since 0.4 already :)

**Comment by rafalp** [comment]
Fixed in 0.5
