### ISSUE TITLE
Sound issues perhaps related to sound source priorities

### ISSUE THREAD

**Issue by Harmalarm** [dethrace-labs/dethrace#183]
I just played Dethrace for the first time. **Impressive** work! 

I noticed the audio is quite off. First off it is quite loud compared to other applications. 
Second the car sounds are being presented a bit weird. The player car sounds are often overruled by opponent car sounds, and sometimes the player car sound is completely omitted, but then pops back when the player enters a different area of the map. 

I think I remember that opponent car sounds were not even present in the original, but I might be wrong there? Anyway, they might have had similar issues and decided to tone them down or give them less priority. There might be some traces of that in de code, but that could also be wishfull thinking. 

Just thought I'd put it out there

**Comment by dethrace-labs** [comment]
I have the issue on my machine that the audio level is loud compared to other apps, glad to have your confirmation its not just my machine! I've noticed that it can get a bit distorted with other cars around too. Thanks for the report!

**Comment by dethrace-labs** [comment]
I think this should be resolved by https://github.com/dethrace-labs/dethrace/pull/228, feel free to re-open if you still think something is off.
