### ISSUE TITLE
Missing texture on Mayan Mayhem track

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#187]
<img width="1440" alt="Zrzut ekranu 2022-09-29 o 18 57 22" src="https://user-images.githubusercontent.com/750553/193093489-7e695c72-bd5c-4849-aebc-d544d4150e34.png">

<img width="1440" alt="Zrzut ekranu 2022-09-29 o 18 59 37" src="https://user-images.githubusercontent.com/750553/193093531-28aa98b6-1041-4ab5-9cee-8ce3f3128579.png">

**Comment by dethrace-labs** [comment]
Can reproduce, looking into it!
