### ISSUE TITLE
Damaged cars smoke underwater

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#193]
Damaged cars smoke when underwater. I don't remember this being the case in original:

<img width="1440" alt="Zrzut ekranu 2022-09-30 o 19 57 43" src="https://user-images.githubusercontent.com/750553/193332329-3dfa4f85-828d-4892-8c92-ffcba7af8449.png">

**Comment by madebr** [comment]
This should be checked again in current master.
#237 improved underwater behavior.

**Comment by madebr** [comment]
I just verified current master makes the smoke disappear from wrecks + own car.
