### ISSUE TITLE
Electro-bastard ray from Electric Blue is not always rendered when she's opponent

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#200]
It seems that frequently peds just drop dead when Electric Blue just passes near them.

**Comment by rafalp** [comment]
Having raced some more with Stella I am not sure if those peds dropping dead weren't caused by different bug and its just coincidence that Stella was nearby. I'll see if I can reproduce this.

**Comment by madebr** [comment]
Before wasting time on this, I'd wait until the next release which carries a fix for erroneously killing peds (https://github.com/dethrace-labs/dethrace/commit/3a9c037939ba81f4ad5eb79fb3d4807953d2f45d).

**Comment by classilla** [comment]
There's a situation where killing peds in Carm^WDethrace is erroneous? *scnr*

**Comment by madebr** [comment]
I'm going to close this issue and assume it got fixed by https://github.com/dethrace-labs/dethrace/pull/189
Please create a new issue if you can provide a reproducer.
