### ISSUE TITLE
Backtrop is drawn in some arenas that don't have it.

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#204]
Armourgeddon race, inside the castle in dethrace:

<img width="752" alt="Zrzut ekranu 2022-10-2 o 20 38 17" src="https://user-images.githubusercontent.com/750553/193470462-a362ae1d-ee9c-4611-8462-ad2b2a400cea.png">

Original cuts backtrop image in this area:

<img width="697" alt="Zrzut ekranu 2022-10-2 o 20 40 40" src="https://user-images.githubusercontent.com/750553/193470552-673033e1-745f-411b-89b1-76b1a850ba48.png">

On [this video](https://www.youtube.com/watch?v=Ya7fVnPd58k) you can see that game stops drawing backtrop around 2:00.

**Comment by dethrace-labs** [comment]
Can replicate. Caused by us not implementing special volumes yet. Will take this one
