### ISSUE TITLE
Armourgedon race doesn't respect difficulty settings for starting time

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#207]
"Armourgeddon" race in Splat Pack starts with 1:30 on clock, even if difficulty is set to easy and it should be 3:00

**Comment by dethrace-labs** [comment]
"Armourgeddon" race is CASTLE.TXT, which has the following initial timer values
```
90,60,30							// Initial timer count for each skill level
```

I tried all difficulties, and the initial timer is correct based on the config in the race file.  Feel free to re-open the issue if you can still repro incorrect behavior that I can't see.
