### ISSUE TITLE
Rendered area is not maxed out to fill a window

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#211]
When game starts, default screen is not maxed, having black border around it:

<img width="752" alt="Zrzut ekranu 2022-10-10 o 00 23 25" src="https://user-images.githubusercontent.com/750553/194782224-b9601c94-c803-472a-832e-67ce679ecc32.png">

**Comment by dethrace-labs** [comment]
This is working as far as I can tell as expected. You can use the "+" and "-" keys to resize the render size. The default size is read from `OPTIONS.TXT`
