### ISSUE TITLE
Skidmarks from wall driving are horizontal

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#220]
If you drive on the wall, skidmarks will be rendered horizontally vs vertically:

<img width="1440" alt="Zrzut ekranu 2022-10-20 o 00 15 05" src="https://user-images.githubusercontent.com/750553/197062493-31903d72-44af-4a12-b403-02acf2fad9c2.png">

**Comment by madebr** [comment]
This is fixed by #233
