### ISSUE TITLE
No Music

### ISSUE THREAD

**Issue by Bugaboo2000** [dethrace-labs/dethrace#278]
Is the music working on dethrace? Otherwise I made a temporary solution, making a sh file with this code:
`playsound $HOME/.local/share/Steam/steamapps/common/Carmageddon1/CARMA/MUSIC/* --loop | $HOME/.local/share/Steam/steamapps/common/Carmageddon1/CARMA/dethrace -sound 4 -hires`

**Comment by dethrace-labs** [comment]
CD audio emulation is not currently implemented. Will leave this issue open as a placeholder
