### ISSUE TITLE
Player car engine sound sometimes cuts out

### ISSUE THREAD

**Issue by dethrace-labs** [dethrace-labs/dethrace#281]
When driving around other cars, especially after a crash, the players car audio seems to stop in favor of the AI cars engine sound. Once you drive far enough away from the AI car, the players engine sound resumes.

Haven't confirmed this is not an OG bug also yet.

**Comment by zear** [comment]
This happens for cars which use the same engine sound samples.
Basically, while each car has a separate sound channel to allow for individual pitch/volume/position changes, if they use the same sound id, they will point to the same descriptor and in turn operate on the same sound buffer. Effectively, the last car to use the sound buffer will override any previous effects on the sample.

This is not the case for OG, which is somehow able to mix multiple channels using the same samples.

**Comment by zear** [comment]
Here is my fix proposal: https://github.com/dethrace-labs/dethrace/pull/286
