### ISSUE TITLE
What are default keys to drive?

### ISSUE THREAD

**Issue by miratcan** [dethrace-labs/dethrace#290]
Arrow keys rotating the camera angle.

**Comment by madebr** [comment]
The numpad keys.
This wiki article documents most of them: https://carmageddon.fandom.com/wiki/Controls

The settings menu should display them as well.

**Comment by dethrace-labs** [comment]
Feel free to use github discussions for questions like this 👍  https://github.com/dethrace-labs/dethrace/discussions/categories/q-a
