### ISSUE TITLE
Smack video is corrupted in hi-res mode (and a bit in normal mode)

### ISSUE THREAD

**Issue by madebr** [dethrace-labs/dethrace#306]
After applying the patch, suggested in https://github.com/dethrace-labs/dethrace/issues/305#issue-1675860843,
the smack video in hi-res mode looks as following:
![image](https://user-images.githubusercontent.com/4138939/233237146-8748521c-b626-4cab-9ccc-c0a92a8e9492.png)

the smack video in normal mode looks as following:
![image](https://user-images.githubusercontent.com/4138939/233237251-f6e339ab-df13-40ad-b0e3-f19935d41c8f.png)
(note the slight corrupted line at the bottom)

This happens because `smackw32.c` blindly copies the smacker buffer to screen whereas it should do e.g. row doubling for hi-res mode,
and handle the difference in dimensions between the source and target buffer.
Or we dynamically change the window dimension.

https://github.com/dethrace-labs/dethrace/blob/6c0b26cc8d72c21d4152adee3328aa88a3c95363/src/DETHRACE/common/cutscene.c#L97

https://github.com/dethrace-labs/dethrace/blob/6c0b26cc8d72c21d4152adee3328aa88a3c95363/src/smackw32/smackw32.c#L59-L73

I don't understand why the width of the video is handled correctly. I would have expected the hi-res video to be scaled by 2 as well.

**Comment by dethrace-labs** [comment]
thanks. The issue was we were copying from smack frame to video assuming the same width for both. The pixel-doubling is taken care of in `PDScreenBufferSwap`

Fixed in https://github.com/dethrace-labs/dethrace/commit/d3fe4ed5d956b7fabcd5fbdc2da3fa43abe1e58c
