### ISSUE TITLE
No smoke is drawn in right half of screen

### ISSUE THREAD

**Issue by madebr** [dethrace-labs/dethrace#310]
This happens in cockpit mode (320x200):
![DUMP0025](https://user-images.githubusercontent.com/4138939/234132299-7d1bfa46-2d50-45e0-a52e-04fb384ce7f8.PNG)
Also in hi-res mode (640x400):
![DUMP0025b](https://user-images.githubusercontent.com/4138939/234132915-2752fd74-9187-4fa3-b9ff-a416340af62b.PNG)
This also happens with smoke emitted by opponents:
![DUMP0025c](https://user-images.githubusercontent.com/4138939/234133062-a1b7c8c0-75a5-453e-bf02-1e476c674f74.PNG)

Tested on current main: 35a4ce83dfb03e10f504416117410c4e381e90f8

**Comment by dethrace-labs** [comment]
Hmm, I cannot repro this on OSX. I'll check on my windows box. Could you check backwards to see when it was introduced? Maybe https://github.com/dethrace-labs/dethrace/pull/295 ?

**Comment by madebr** [comment]
It's ef9e4d668d799ab31b998a8e7877e36c8af4fe44

Look how the smoke stops at half the screen, but bleeds a little in the right half.
![DUMP0055](https://user-images.githubusercontent.com/4138939/234603436-b852ee31-07ce-4187-925f-a97dfba2de70.PNG)

The fog depth effect also broke in the same commit.
before:
![DUMP0056](https://user-images.githubusercontent.com/4138939/234603776-72602b8b-4fa2-4ea8-b8e7-520e6f32a782.PNG)
after:
![DUMP0058](https://user-images.githubusercontent.com/4138939/234603841-fce18161-8c93-4e9e-88a3-fd3f9edf4ce2.PNG)

So perhaps the depth buffer is used/updated wrong?

**Comment by madebr** [comment]
Reducing the viewport by using the <kbd>-</kbd> key makes the smoke appear again.
