### ISSUE TITLE
Feature Request: Fullscreen on startup / -f for fullscreen

### ISSUE THREAD

**Issue by Gagert** [dethrace-labs/dethrace#344]
This may be related to Issue #72 as that also covered fullscreen mode, but I haven't found any way to get dethrace in fullscreen at startup with something like a -f command or anything.

The oldschool Alt + Enter combination works, but this has to be pressed everytime I start dethrace. Having a standard -f argument that can be typed in a *.bat file just like the -hires command could hypothetically always make dethrace launch at fullscreen mode.

I've tested both the latest compiled build (4200cfa) and the laters released build (0.6.0) on Windows 11 to see if dethrace can be launched in fullscreen, and haven't found any way yet.

**Comment by jeff-1amstudios** [comment]
Good idea

**Comment by madebr** [comment]
Does `--full-screen` work for you?
https://github.com/dethrace-labs/dethrace/blob/4200cfab6c20d484d3b55b58281a7b43ec32b439/src/harness/harness.c#L248-L250

**Comment by Gagert** [comment]
Yes, this worked flawlessly.

I tried earlier on --fullscreen in one word; it could be beneficial if this was in the readme.md on the front page of the dethrace Github page.

**Comment by madebr** [comment]
We need to add our custom flags to `-h`.
