### ISSUE TITLE
Render glitches while in in-car view

### ISSUE THREAD

**Issue by Gagert** [dethrace-labs/dethrace#350]
Using build 4200cfa on Windows 11, there seems to be various rendering glitches while in in-car view. You can see colored trails of the cars passing by at the start of the match, while at the middle of the image the skybox & environments at the center of the view is glitching & duplicating.

The rear mirror is currently black (known issue I suppose); I don't know if the game has to be rendered twice to show the rear mirror view, or what kind of tricks the game originally used to achieve this effect.

![carma in-car bug](https://github.com/dethrace-labs/dethrace/assets/8365446/0e02ae47-c7af-4350-a2a5-8be724bfc0b8)

**Comment by dethrace-labs** [comment]
Fixed by https://github.com/dethrace-labs/dethrace/pull/363
