### ISSUE TITLE
Improve support for the Brazilian Portuguese version

### ISSUE THREAD

**Issue by leomontenegro6** [dethrace-labs/dethrace#352]
A few months ago, I found out this cool reverse engineering project of Carmageddon. Glad it worked fine not only in PC, but also in some linux-based portable devices, such as Anbernic ones.

The original game works fine, but out of my curiosity, I tested if dethrace wouldn't, for some reason, support the [Brazilian Portuguese version](https://archive.org/details/Carma) of this game, that features lots of texts and graphical changes, and even voice dubbing. It worked to some extend, but lots of menus were bugged. It worked in the Windows PC version, but crashed in Linux when I tried to run in my device with [the binary compiled by PortMaster](https://portmaster.games/detail.html?name=carmageddon). Not sure if it's something from the compilation, or if it's really an issue with any dethrace linux versions.

Is there a chance we could improve dethrace to fully support this version?

**Comment by madebr** [comment]
I just tested dethrace of current master with the Portuguese game data, and some menus indeed cause a segmentation fault (e.g. the Race Selection Menu).

About the menus, if you're talking about the text disappearing and re-appearing when hovering your mouse, I think OG also has this.
See [this video](https://youtu.be/5J82nMjJstM?t=137): the text also disappears there.
This behavior also occurs with German game data.

The options menu also looks bugged.

**Comment by madebr** [comment]
With #353, Portuguese dethrace does not crash anymore in the menus.

**Comment by leomontenegro6** [comment]
Oh, that's pretty cool. I'll let PortMaster guys know about this update, and see if we can recompile it. Not sure if we're gonna do that with master, or after a new stable version is released with these changes.

About the YT video above, is there a difference between grabbing original game and merging the translated files with it, or getting all the data directly from a PT-BR ISO image? Is the result going to be the same, or did the author make some changes to accommodate the files with the original game?
