### ISSUE TITLE
Start in little window

### ISSUE THREAD

**Issue by Paskale84** [dethrace-labs/dethrace#361]
[
![IMG_20240420_183124_997](https://github.com/dethrace-labs/dethrace/assets/117976095/112a9856-0c32-4933-8700-322f082f1477)
]
I have this problem...

**Comment by Paskale84** [comment]
I have add -hires but remain this little window

**Comment by dethrace-labs** [comment]
Try —full-screen?

**Comment by dethrace-labs** [comment]
I’m curious - does the game itself actually run? Are you able to set up the controls?

**Comment by Paskale84** [comment]
Trimui smart pro

**Comment by Paskale84** [comment]
No --full-screen no change.

**Comment by Paskale84** [comment]
![IMG_2024_04_22_20_37_34_7772384679193929732616](https://github.com/dethrace-labs/dethrace/assets/117976095/de990e75-74d8-4c8f-a542-0326fd62b49e)

**Comment by Paskale84** [comment]
I try whit USB keyboard and alt+enter stretch image to full, but on reload a game the problem return.

**Comment by dethrace-labs** [comment]
Hmm ok, when you alt+enter it goes fullscreen even during gameplay? Could you capture a few pictures of driving around?!

**Comment by Paskale84** [comment]
![IMG_2024_04_23_00_23_34_5519199232176595165486](https://github.com/dethrace-labs/dethrace/assets/117976095/3186616f-4713-4a54-90a6-b3613207c690)

**Comment by Paskale84** [comment]
![Screenshot_20240423-003202](https://github.com/dethrace-labs/dethrace/assets/117976095/42f37614-f8d6-495c-85af-0688c225abd6)
The problem is before ./dethrace all prefix before not start a game and turn on menu

**Comment by Paskale84** [comment]
Is possible a shell command for alt+enter without a keyboard ?

**Comment by Paskale84** [comment]
Yes solved, thanks and have add -hires for svga and work!
