### ISSUE TITLE
Unable to save/load game

### ISSUE THREAD

**Issue by Beobachten** [dethrace-labs/dethrace#367]
As of the current PR version 0.7.1, both windows builds for win32 and x64 do not currently allow the player to save progress of the game and consequently, they are unable to load any saved games.
I tested both builds to double check the issue.

I recorded a quick video to demonstrate the issue here https://drive.google.com/file/d/1lqQaq9qgTkl-sbP4BGbepnsiBQJNrba-/view?usp=sharing 

This doesn't seem to be an issue with the macos build from what I saw in the discord discussion and I am unaware if the same issue affects the linux builds as well.

**Comment by madebr** [comment]
https://github.com/dethrace-labs/dethrace/pull/372 will fix this

The msdn documentation mentions `fopen_s` and `_wfopen_s` functions can't open a file for sharing,
