### ISSUE TITLE
question for a port on the ds(i)

### ISSUE THREAD

**Issue by EhanMMMZET** [dethrace-labs/dethrace#420]
hi, is it possible to compile a port for the ds or dsi?

**Comment by madebr** [comment]
We don't know! You tell us :)

- Upstream SDL2 supports n3ds, so input and video should work.
- I don't think miniaudio supports n3ds, so audio won't work/compile.
- Jeff did an impressive job in BRender to make it build on aarch64 by implementing all assembly into C, so that should work.
- dethrace itself is also implemented in portable C
- n3ds will need an implementation for [a few harness functions](https://github.com/dethrace-labs/dethrace/tree/main/src/harness/os)

I'm curious what the performance would be.
Get in touch with us if you're interested in working on a port.
(You can post here, or on the Discord server)

**Comment by EhanMMMZET** [comment]
> We don't know! You tell us :)
> 
> 
> 
> - Upstream SDL2 supports n3ds, so input and video should work.
> 
> - I don't think miniaudio supports n3ds, so audio won't work/compile.
> 
> - Jeff did an impressive job in BRender to make it build on aarch64 by implementing all assembly into C, so that should work.
> 
> - dethrace itself is also implemented in portable C
> 
> - n3ds will need an implementation for [a few harness functions](https://github.com/dethrace-labs/dethrace/tree/main/src/harness/os)
> 
> 
> 
> I'm curious what the performance would be.
> 
> Get in touch with us if you're interested in working on a port.
> 
> (You can post here, or on the Discord server)

firstly, cool and secondly, i don't have enough experience with compiling and building code so i don't think i'll be able to build this port, but i'd be happy to see someone else do!

**Comment by EhanMMMZET** [comment]
> We don't know! You tell us :)
> 
> 
> 
> - Upstream SDL2 supports n3ds, so input and video should work.
> 
> - I don't think miniaudio supports n3ds, so audio won't work/compile.
> 
> - Jeff did an impressive job in BRender to make it build on aarch64 by implementing all assembly into C, so that should work.
> 
> - dethrace itself is also implemented in portable C
> 
> - n3ds will need an implementation for [a few harness functions](https://github.com/dethrace-labs/dethrace/tree/main/src/harness/os)
> 
> 
> 
> I'm curious what the performance would be.
> 
> Get in touch with us if you're interested in working on a port.
> 
> (You can post here, or on the Discord server)

and uhh i mean the original nintendo ds, 3ds port can also be good

**Comment by EhanMMMZET** [comment]
i've done some research and found that sdl IS supported on the original ds(i), secondly i believe armkitpro can provide audio playback and other compiling, so with a bit of work it could work

**Comment by madebr** [comment]
That's awesome to hear. A few months ago, I backported dethrace to SDL 1.2 so that can be used as a starting point for devs interesed.
https://github.com/madebr/dethrace/tree/sdl-1.2

I'll leave it up to you to find a motivated ds developer :)

**Comment by EhanMMMZET** [comment]
> That's awesome to hear. A few months ago, I backported dethrace to SDL 1.2 so that can be used as a starting point for devs interesed.
> 
> https://github.com/madebr/dethrace/tree/sdl-1.2
> 
> 
> 
> I'll leave it up to you to find a motivated ds developer :)

ok, why not
