### ISSUE TITLE
Hello! Can you please add a percentage tracker, that eg. 70% of the functions are reversed to C ?

### ISSUE THREAD

**Issue by xcom169** [dethrace-labs/dethrace#55]
Hello! Can you please add a text based percentage tracker, that eg. 70% of the functions are reversed to C ?

Thanks,

**Comment by jeff-1amstudios** [comment]
Good idea - I’ll have a look at how we can do this. Every method that isn’t implemented has a NOT_IMPLEMENTED() guard on it, so probably with a bit of grep / python script hackery it shouldn’t be too hard
