### ISSUE TITLE
Replace SDL2 with GLFW

### ISSUE THREAD

**Issue by jeff-1amstudios** [dethrace-labs/dethrace#56]
We don’t really use any SDL functionally that isn’t present in the lighter weight GLFW

**Comment by xcom169** [comment]
Currently you use SDL2 for the graphics, or OpenGL?

**Comment by dethrace-labs** [comment]
We use OpenGL, plus some SDL code for handling the setup. After creating this, I'm not super sure about it - it seems like SDL might give us more flexibility if we ever (who knows) want to build for Android. Either way, the code difference doesn't seem too major
