### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [dethrace-labs/dethrace#61]
I was wondering if there is some support for playing the [Carmageddon demo](https://archive.org/details/carmdemo) (It will allow to test the game without buying the full game).

**Comment by jeff-1amstudios** [comment]
Thanks for opening the issue! It’s definitely our intention to support the demo content for exactly the reason you gave, along with the goal of preserving history.

I’ll take a look at what needs to be down to get this working - hopefully the only thing to do is to implement the demo data file decryption - I think the decryption keys changed between the demo and retail versions

**Comment by xcom169** [comment]
Hello All! Currently only the GOG version working with this binary?

**Comment by dethrace-labs** [comment]
We're pretty early in the project, but yes, GOG version is working (no textures yet though)

**Comment by neuromancer** [comment]
Great news. Can we expect a release soon?
