### ISSUE TITLE
The game is not available/region locked in some countries

### ISSUE THREAD

**Issue by frostworx** [dethrace-labs/dethrace#63]
_(found your project [here on r/linux_gaming](https://www.reddit.com/r/linux_gaming/comments/put96j/dethrace_carmageddon_reimplementation_based_on/))_

Thanks for your hard work! The code compiles fine ootb!
Unfortunately the game itself is region locked at least in germany and therefore can't be purchased neither on gog nor on steam
without workarounds.
Maybe this is worth to be mentioned in your `README`?

**Comment by jeff-1amstudios** [comment]
Maybe https://github.com/dethrace-labs/dethrace/issues/61 will help?

**Comment by frostworx** [comment]
Thanks for the pointer, this will help indeed when #61 is fixed. _(subscribed #61, so I won't forget it)_
