### ISSUE TITLE
Crash when selecting "View Racers" in the "Start Race" menu

### ISSUE THREAD

**Issue by plaes** [dethrace-labs/dethrace#75]
Managed to run into following crash when in the "Start Race" menu selected "View Info" -> "View Racers" button

Stack trace:
0: MemReadU32 at dethrace/src/DETHRACE/common/loading.c:220
1: StartFlic at dethrace/src/DETHRACE/common/flicplay.c:689
2: ChangePanelFlic at dethrace/src/DETHRACE/common/flicplay.c:1730
3: SetOpponentFlic at dethrace/src/DETHRACE/common/racestrt.c:386
4: DrawSceneyMappyInfoVieweyThing at dethrace/src/DETHRACE/common/racestrt.c:397 
5: StartRaceGoAhead at dethrace/src/DETHRACE/common/racestrt.c:447
6: DoInterfaceScreen at dethrace/src/DETHRACE/common/intrface.c:413
7: DoSelectRace at dethrace/src/DETHRACE/common/racestrt.c:804
8: DoGame at dethrace/src/DETHRACE/common/structur.c:319
9: DoProgram at dethrace/src/DETHRACE/common/structur.c:506
10: GameMain at dethrace/src/DETHRACE/common/main.c:96
11: original_main at dethrace/src/DETHRACE/pc-dos/dossys.c:690
12: main at dethrace/src/DETHRACE/main.c:30

Happens with current master ba4b7630fbb

**Comment by dethrace-labs** [comment]
thanks for the report. Yes, the menu UI is implemented only enough to get straight through to the default race. Can't choose race, or view opponents, or really anything else :)

**Comment by dethrace-labs** [comment]
Yet!
